---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)

```

## Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")

names(litters_df)

litters_df = janitor::clean_names(litters_df)

```

## Take a look at the data

Printing in the console.

```{r}
litters_df
```

```{r}
head(litters_df)
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

# Arguments in read_csv

```{r}
litters_df1 = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5, 
    col_names = FALSE, 
    na = "Low8")

```

```{r}
litters_data = read_csv( "./data/FAS_litters.csv",
    col_types = cols(
      Group = col_character(),
      'Litter Number' = col_character(),
      'GD0 weight' = col_double(),
      'GD18 weight' = col_double(),
      'GD of Birth' = col_integer(),
      'Pups born alive' = col_integer(),
      'Pups dead @ birth' = col_integer(),
      'Pups survive' = col_integer()
      )
    )

```


read in an excel file.

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
```

read in a SAS file
```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
```

